#include "Uses.h"

const std::unordered_map<ArgumentType, std::unordered_set<ArgumentType>> Uses::validationTable {
        {
            ASSIGN_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            PRINT_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            IF_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            WHILE_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            CALL_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            PROCEDURE_SYNONYM,
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            NUMBER, // Line number of statement
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        },
        {
            ACTUAL_NAME,    // Actual name of procedure, i.e. "prod1"
            {
                VAR_SYNONYM,
                ACTUAL_NAME
            }
        }
};