name: CI for Cmake Project - MacOS

on:
  push:
    branches:
      - master
      - source-processor-branch
      - automated-testing-branch
#  pull_request:
#    branches:
#      - master
#      - source-processor-branch

#on:
#  schedule:
#    - cron: "0 23 * * *"

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 7
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team26/Code26/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Test cd
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          pwd
          ls
          cd Code26
          pwd
          ls
          cd build
          pwd
          ls
          cd src
          pwd
          ls
          cd autotester
          pwd
          ls

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Run Unit Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cd src/unit_testing
          ./unit_testing -d yes -o output.txt
          echo UNIT TESTING
          cat output.txt

      - name: Run Integration Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cd src/integration_testing
          ./integration_testing -d yes -o output.txt
          echo INTEGRATION TESTING
          cat output.txt

      - name: Run autotester test cases
        shell: bash
        run: |
          cd Team26/Tests26
          python ./run_tests.py