name: CI for Cmake Project - MacOS

on:
  push:
    branches:
      - master
      - source-processor-branch
      - automated-testing-branch
  pull_request:
    branches:
      - master

#on:
#  schedule:
#    - cron: "0 23 * * *"

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 7
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team26/Code26/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Run Unit Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cd src/unit_testing
          ./unit_testing -d yes -o output.txt
          echo UNIT TESTING
          cat output.txt

      - name: Run Integration Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cd src/integration_testing
          ./integration_testing -d yes -o output.txt
          echo INTEGRATION TESTING
          cat output.txt

      - name: Run autotester test cases
        if: always()
        shell: bash
        working-directory: ${{runner.workspace}}/22s1-cp-spa-team-26
        run: |
          cd Team26/Tests26
          python ./run_tests.py

      - name: Archive Test Results Error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Failed logs and out.xml
          path: |
            ${{runner.workspace}}/22s1-cp-spa-team-26/Team26/Tests26/failed_tests.txt
            ${{runner.workspace}}/22s1-cp-spa-team-26/Team26/Tests26/failed_tests/
          retention-days: 3

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: binaries
          path: |
            ${{runner.workspace}}/build/src/integration_testing/integration_testing
            ${{runner.workspace}}/build/src/unit_testing/unit_testing
            ${{runner.workspace}}/build/src/autotester/autotester
          retention-days: 3