name: Build, Unit, Integration & System Tests - Windows

on:
  push:
    branches:
      - master
      - source-processor-branch
      - automated-testing-branch
  pull_request:
    branches:
      - "**"

# If you are doing triggering your workflow from pushes or merging more than twice a day on average,
# please execute your workflow on a schedule instead.
# Comment the above 7 lines, and uncomment the following 3 lines
# on:
#   schedule:
#     - cron: "0 09,23 * * *"

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 7
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build Project
        shell: bash
        run: |
          cd Team26/Code26
          mkdir build
          cd build
          cmake ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          cd ../..

      - name: Run Unit Tests
        shell: bash
        run: |
          cd Team26
          cd Code26
          cd build
          cd src
          cd unit_testing
          cd Release
          ./unit_testing.exe -d yes -o output.txt
          echo UNIT TESTING
          cat output.txt

      - name: Run Integration Tests
        shell: bash
        run: |
          cd Team26
          cd Code26
          cd build
          cd src
          cd integration_testing
          cd Release
          echo INTEGRATION TESTING
          ./integration_testing.exe -d yes -o output.txt
          cat output.txt

      - name: Run autotester test cases
        if: always()
        shell: bash
        run: |
          cd Team26
          cd Tests26
          python run_tests.py

      - name: Archive Test Results Error
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: results
          path: |
            Team26\Tests26\failed_tests.txt
            Team26\Tests26\failed_tests\
          retention-days: 3

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: binaries
          path: |
            Team26/Code26/build/src/autotester/Release/autotester.exe
            Team26/Code26/build/src/unit_testing/Release/unit_testing.exe
            Team26/Code26/build/src/integration_testing/Release/integration_testing.exe
          retention-days: 3

      - name: Setup OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources HelloCov --export_type cobertura:HelloCov.xml -- "vstest.console.exe" Debug\HelloTest.dll

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./HelloCov.xml
          fail_ci_if_error: true
          functionalities: fix