#name: Reviewdog
#on:
#  pull_request:
#    branches:
#      - "**"
#
#jobs:
#  cpplint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: reviewdog/action-cpplint@master
#        with:
#          github_token: ${{ secrets.github_token }}
#          reporter: github-pr-review
#          filter: "-legal/copyright" # Optional